---

- name: "configuration play." 
  hosts: web
  user: "ubuntu"
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: Accept EC2 SSH host keys
      connection: local
      become: true
      shell: |
        ssh-keygen -F {{ inventory_hostname }} || 
          ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
        ssh-add ~/.ssh/id_rsa
      register: known_hosts_script
      changed_when: "'found' not in known_hosts_script.stdout"

  roles:
    # Your code here
    - deploy