---

- name: "configuration play." 
  hosts: web
  user: "ubuntu"
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: Accept EC2 SSH host keys
      connection: local
      become: false
      shell: |
        ssh-keygen -F {{ inventory_hostname }} || 
          ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
      register: known_hosts_script
      changed_when: "'found' not in known_hosts_script.stdout"
      
    - name: wait for target connection to become reachable/usable.
      # Your code here
      wait_for_connection:
        timeout: 300
      shell: |
        exit 0

  roles:
    # Your code here
    - deploy