---
- name: upgrade packages
  yum:
    name: upgrade
    state: lastest

- name: install nodejs
  yum:
    name: nodejs
    state: present

- name: install npm
  yum:
    name: npm
    state: present

- name: install pm2
  yum:
    name: pm2
    state: present